name: frontend_mvvc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/notes.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/notes.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/notes.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/notes.png"
flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/